# Generated by Django 4.0.3 on 2022-03-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('gender', models.CharField(choices=[('women', 'women'), ('man', 'man'), ('other', 'other')], max_length=5, verbose_name='Пол')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('avatar', models.ImageField(upload_to='avatars/', verbose_name='Аватарка')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
