# Generated by Django 4.0.3 on 2022-03-14 17:44

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.ImageField(upload_to='avatars/', validators=[clients.models.file_size], verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('жен', 'women'), ('муж', 'man'), ('другое', 'other')], max_length=6, verbose_name='Пол'),
        ),
    ]
